spring:
  application:
    name:PartyPlanner

  datasources:
    url: ${DB_URL}
    usermae: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enable: true

  cache:
    redis:
      time-to-live: 6000