spring:
  application:
    name: PartyPlanner

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 6000
