name: Build and Deploy EC2 by Leozinho

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Build Maven artifact
      - name: Build artifact
        run: mvn clean package

      # 4️⃣ Copy .jar and run it on EC2
      - name: Deploy artifact to EC2
        run: |
          # Create private key file
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy the .jar to EC2, ignoring host verification
          scp -i private_key.pem -o StrictHostKeyChecking=no ./target/PartyPlanner-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/
          
          # Run the .jar in background on EC2, ignoring host verification
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          nohup java -jar /home/ec2-user/PartyPlanner-0.0.1-SNAPSHOT.jar > /home/ec2-user/output.log 2>&1 &
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
